"""add_reports_settings_models

Revision ID: 0396f7553cbd
Revises: c32e7d84a5b1
Create Date: 2026-07-12 16:06:48.034942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0396f7553cbd'
down_revision: Union[str, None] = 'c32e7d84a5b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('esg_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('environmental_weight', sa.Float(), nullable=False),
    sa.Column('social_weight', sa.Float(), nullable=False),
    sa.Column('governance_weight', sa.Float(), nullable=False),
    sa.Column('auto_carbon_calculation', sa.Boolean(), nullable=False),
    sa.Column('evidence_required', sa.Boolean(), nullable=False),
    sa.Column('auto_badge_award', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('export_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('export_format', sa.String(length=10), nullable=False),
    sa.Column('exported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exported_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['exported_by'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('email_alerts', sa.Boolean(), nullable=False),
    sa.Column('compliance_alerts', sa.Boolean(), nullable=False),
    sa.Column('challenge_updates', sa.Boolean(), nullable=False),
    sa.Column('badge_milestones', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_settings_profile_id'), 'notification_settings', ['profile_id'], unique=True)
    op.create_table('report_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_templates')
    op.drop_index(op.f('ix_notification_settings_profile_id'), table_name='notification_settings')
    op.drop_table('notification_settings')
    op.drop_table('export_audit_logs')
    op.drop_table('esg_configurations')
    # ### end Alembic commands ###
