"""add environmental models

Revision ID: 4985e406f161
Revises: 7b6aaaaaf498
Create Date: 2026-07-12 14:32:46.668588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4985e406f161'
down_revision: Union[str, None] = '7b6aaaaaf498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emission_factors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('factor_code', sa.String(length=50), nullable=False),
    sa.Column('factor_name', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('co2e_factor', sa.Float(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='factorstatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('co2e_factor >= 0', name='check_positive_co2e_factor'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emission_factors_factor_code'), 'emission_factors', ['factor_code'], unique=True)
    op.create_index(op.f('ix_emission_factors_factor_name'), 'emission_factors', ['factor_name'], unique=False)
    op.create_table('environmental_goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('goal_name', sa.String(length=255), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('target_co2', sa.Float(), nullable=False),
    sa.Column('current_co2', sa.Float(), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ON_TRACK', 'AT_RISK', 'COMPLETED', 'MISSED', name='goalstatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('current_co2 >= 0', name='check_positive_current_co2'),
    sa.CheckConstraint('progress_percentage >= 0 AND progress_percentage <= 100', name='check_valid_progress_percentage'),
    sa.CheckConstraint('target_co2 >= 0', name='check_positive_target_co2'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environmental_goals_department_id'), 'environmental_goals', ['department_id'], unique=False)
    op.create_table('carbon_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_number', sa.String(length=50), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('product_esg_profile_id', sa.UUID(), nullable=True),
    sa.Column('emission_factor_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('calculated_emission', sa.Float(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'LOGGED', 'VERIFIED', name='transactionstatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('calculated_emission >= 0', name='check_positive_calculated_emission'),
    sa.CheckConstraint('quantity >= 0', name='check_positive_quantity'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['emission_factor_id'], ['emission_factors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_esg_profile_id'], ['product_esg_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carbon_transactions_department_id'), 'carbon_transactions', ['department_id'], unique=False)
    op.create_index(op.f('ix_carbon_transactions_product_esg_profile_id'), 'carbon_transactions', ['product_esg_profile_id'], unique=False)
    op.create_index(op.f('ix_carbon_transactions_transaction_date'), 'carbon_transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_carbon_transactions_transaction_number'), 'carbon_transactions', ['transaction_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_carbon_transactions_transaction_number'), table_name='carbon_transactions')
    op.drop_index(op.f('ix_carbon_transactions_transaction_date'), table_name='carbon_transactions')
    op.drop_index(op.f('ix_carbon_transactions_product_esg_profile_id'), table_name='carbon_transactions')
    op.drop_index(op.f('ix_carbon_transactions_department_id'), table_name='carbon_transactions')
    op.drop_table('carbon_transactions')
    op.drop_index(op.f('ix_environmental_goals_department_id'), table_name='environmental_goals')
    op.drop_table('environmental_goals')
    op.drop_index(op.f('ix_emission_factors_factor_name'), table_name='emission_factors')
    op.drop_index(op.f('ix_emission_factors_factor_code'), table_name='emission_factors')
    op.drop_table('emission_factors')
    # ### end Alembic commands ###
