"""Add ProductESGProfile table

Revision ID: 7b6aaaaaf498
Revises: 9ad25f4024cb
Create Date: 2026-07-12 13:54:20.218748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b6aaaaaf498'
down_revision: Union[str, None] = '9ad25f4024cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_esg_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('carbon_factor', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('carbon_unit', sa.String(length=50), nullable=True),
    sa.Column('sustainability_rating', sa.Enum('BRONZE', 'SILVER', 'GOLD', 'PLATINUM', name='sustainabilityrating'), nullable=True),
    sa.Column('esg_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('recyclable', sa.Boolean(), nullable=True),
    sa.Column('recycled_content_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('renewable_material', sa.Boolean(), nullable=True),
    sa.Column('hazardous_material', sa.Boolean(), nullable=True),
    sa.Column('certification', sa.String(), nullable=True),
    sa.Column('supplier_name', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='productstatus'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_esg_profiles_department_id'), 'product_esg_profiles', ['department_id'], unique=False)
    op.create_index(op.f('ix_product_esg_profiles_esg_score'), 'product_esg_profiles', ['esg_score'], unique=False)
    op.create_index(op.f('ix_product_esg_profiles_product_code'), 'product_esg_profiles', ['product_code'], unique=True)
    op.create_index(op.f('ix_product_esg_profiles_product_name'), 'product_esg_profiles', ['product_name'], unique=False)
    op.create_index(op.f('ix_product_esg_profiles_status'), 'product_esg_profiles', ['status'], unique=False)
    op.create_index(op.f('ix_product_esg_profiles_sustainability_rating'), 'product_esg_profiles', ['sustainability_rating'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_esg_profiles_sustainability_rating'), table_name='product_esg_profiles')
    op.drop_index(op.f('ix_product_esg_profiles_status'), table_name='product_esg_profiles')
    op.drop_index(op.f('ix_product_esg_profiles_product_name'), table_name='product_esg_profiles')
    op.drop_index(op.f('ix_product_esg_profiles_product_code'), table_name='product_esg_profiles')
    op.drop_index(op.f('ix_product_esg_profiles_esg_score'), table_name='product_esg_profiles')
    op.drop_index(op.f('ix_product_esg_profiles_department_id'), table_name='product_esg_profiles')
    op.drop_table('product_esg_profiles')
    # ### end Alembic commands ###
