"""add_employee_fields_to_profiles

Revision ID: 9ad25f4024cb
Revises: e77c082c2909
Create Date: 2026-07-12 13:34:36.488281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ad25f4024cb'
down_revision: Union[str, None] = 'e77c082c2909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('profiles', sa.Column('last_name', sa.String(length=100), nullable=True))
    from sqlalchemy.dialects import postgresql
    genderenum = postgresql.ENUM('MALE', 'FEMALE', 'OTHER', name='genderenum')
    genderenum.create(op.get_bind(), checkfirst=True)

    op.add_column('profiles', sa.Column('manager_id', sa.UUID(), nullable=True))
    op.add_column('profiles', sa.Column('gender', genderenum, nullable=True))
    op.add_column('profiles', sa.Column('joining_date', sa.Date(), nullable=True))
    op.add_column('profiles', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('profiles', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('profiles', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('profiles', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('profiles', 'profile_image',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    statusenum = postgresql.ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', name='statusenum')
    statusenum.create(op.get_bind(), checkfirst=True)
    
    op.alter_column('profiles', 'status',
               existing_type=sa.VARCHAR(),
               type_=statusenum,
               postgresql_using='status::text::statusenum',
               nullable=False)
    op.create_foreign_key(None, 'profiles', 'profiles', ['manager_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.alter_column('profiles', 'status',
               existing_type=sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='statusenum'),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('profiles', 'profile_image',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('profiles', 'deleted_at')
    op.drop_column('profiles', 'is_deleted')
    op.drop_column('profiles', 'address')
    op.drop_column('profiles', 'date_of_birth')
    op.drop_column('profiles', 'joining_date')
    op.drop_column('profiles', 'gender')
    op.drop_column('profiles', 'manager_id')
    op.drop_column('profiles', 'last_name')
    op.drop_column('profiles', 'first_name')
    
    from sqlalchemy.dialects import postgresql
    genderenum = postgresql.ENUM('MALE', 'FEMALE', 'OTHER', name='genderenum')
    genderenum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
