"""add_gamification_models

Revision ID: c32e7d84a5b1
Revises: 8c7e2c58b4ea
Create Date: 2026-07-12 15:32:29.102598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c32e7d84a5b1'
down_revision: Union[str, None] = '8c7e2c58b4ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xp_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xp_transactions_employee_id'), 'xp_transactions', ['employee_id'], unique=False)
    op.create_table('challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('challenge_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('xp_points', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='challengedifficultyenum'), nullable=False),
    sa.Column('evidence_required', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'UPCOMING', 'COMPLETED', 'ARCHIVED', name='challengestatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenges_category_id'), 'challenges', ['category_id'], unique=False)
    op.create_index(op.f('ix_challenges_challenge_code'), 'challenges', ['challenge_code'], unique=True)
    op.create_table('challenge_participation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('proof_url', sa.String(length=500), nullable=True),
    sa.Column('approval_status', sa.Enum('IN_PROGRESS', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', name='participationstatusenum'), nullable=False),
    sa.Column('xp_awarded', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenge_participation_challenge_id'), 'challenge_participation', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_challenge_participation_employee_id'), 'challenge_participation', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_challenge_participation_employee_id'), table_name='challenge_participation')
    op.drop_index(op.f('ix_challenge_participation_challenge_id'), table_name='challenge_participation')
    op.drop_table('challenge_participation')
    op.drop_index(op.f('ix_challenges_challenge_code'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_category_id'), table_name='challenges')
    op.drop_table('challenges')
    op.drop_index(op.f('ix_xp_transactions_employee_id'), table_name='xp_transactions')
    op.drop_table('xp_transactions')
    # ### end Alembic commands ###
