"""add last_login

Revision ID: c56ffa0cdeea
Revises: fbf986e7e3ff
Create Date: 2026-07-12 12:20:26.347082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c56ffa0cdeea'
down_revision: Union[str, None] = 'fbf986e7e3ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('last_login', sa.DateTime(), nullable=True))
    # Removed status column alter because postgres enum creation fails in autogenerate
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'status',
               existing_type=sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='statusenum'),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('profiles', 'last_login')
    # ### end Alembic commands ###
