"""add_governance_models

Revision ID: e2376774f40c
Revises: 4985e406f161
Create Date: 2026-07-12 15:07:18.592924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2376774f40c'
down_revision: Union[str, None] = '4985e406f161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diversity_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('reporting_period', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dept_metric_period', 'diversity_metrics', ['department_id', 'metric_name', 'reporting_period'], unique=True)
    op.create_index(op.f('ix_diversity_metrics_department_id'), 'diversity_metrics', ['department_id'], unique=False)
    op.create_table('esg_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='policystatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_esg_policies_department_id'), 'esg_policies', ['department_id'], unique=False)
    op.create_index(op.f('ix_esg_policies_policy_code'), 'esg_policies', ['policy_code'], unique=True)
    op.create_index(op.f('ix_esg_policies_title'), 'esg_policies', ['title'], unique=False)
    op.create_table('audits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audit_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('auditor_id', sa.UUID(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='auditstatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['auditor_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audits_audit_code'), 'audits', ['audit_code'], unique=True)
    op.create_index(op.f('ix_audits_department_id'), 'audits', ['department_id'], unique=False)
    op.create_table('policy_acknowledgements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACKNOWLEDGED', name='acknowledgementstatusenum'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['esg_policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_acknowledgements_employee_id'), 'policy_acknowledgements', ['employee_id'], unique=False)
    op.create_index(op.f('ix_policy_acknowledgements_policy_id'), 'policy_acknowledgements', ['policy_id'], unique=False)
    op.create_table('training_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('training_name', sa.String(length=255), nullable=False),
    sa.Column('completion_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('certificate_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_records_employee_id'), 'training_records', ['employee_id'], unique=False)
    op.create_table('compliance_issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='issueseverityenum'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='issuestatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_issues_audit_id'), 'compliance_issues', ['audit_id'], unique=False)
    op.create_table('csr_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('activity_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('end_date >= start_date', name='check_csr_dates'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_csr_activities_activity_code'), 'csr_activities', ['activity_code'], unique=True)
    op.create_index(op.f('ix_csr_activities_deleted_at'), 'csr_activities', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_csr_activities_status'), 'csr_activities', ['status'], unique=False)
    op.create_index(op.f('ix_csr_activities_title'), 'csr_activities', ['title'], unique=False)
    op.create_table('employee_participation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('proof_url', sa.String(length=1024), nullable=True),
    sa.Column('approval_status', sa.String(length=20), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.Column('completion_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['csr_activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_employee_activity', 'employee_participation', ['employee_id', 'activity_id'], unique=True)
    op.create_index(op.f('ix_employee_participation_activity_id'), 'employee_participation', ['activity_id'], unique=False)
    op.create_index(op.f('ix_employee_participation_employee_id'), 'employee_participation', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_participation_employee_id'), table_name='employee_participation')
    op.drop_index(op.f('ix_employee_participation_activity_id'), table_name='employee_participation')
    op.drop_index('idx_employee_activity', table_name='employee_participation')
    op.drop_table('employee_participation')
    op.drop_index(op.f('ix_csr_activities_title'), table_name='csr_activities')
    op.drop_index(op.f('ix_csr_activities_status'), table_name='csr_activities')
    op.drop_index(op.f('ix_csr_activities_deleted_at'), table_name='csr_activities')
    op.drop_index(op.f('ix_csr_activities_activity_code'), table_name='csr_activities')
    op.drop_table('csr_activities')
    op.drop_index(op.f('ix_compliance_issues_audit_id'), table_name='compliance_issues')
    op.drop_table('compliance_issues')
    op.drop_index(op.f('ix_training_records_employee_id'), table_name='training_records')
    op.drop_table('training_records')
    op.drop_index(op.f('ix_policy_acknowledgements_policy_id'), table_name='policy_acknowledgements')
    op.drop_index(op.f('ix_policy_acknowledgements_employee_id'), table_name='policy_acknowledgements')
    op.drop_table('policy_acknowledgements')
    op.drop_index(op.f('ix_audits_department_id'), table_name='audits')
    op.drop_index(op.f('ix_audits_audit_code'), table_name='audits')
    op.drop_table('audits')
    op.drop_index(op.f('ix_esg_policies_title'), table_name='esg_policies')
    op.drop_index(op.f('ix_esg_policies_policy_code'), table_name='esg_policies')
    op.drop_index(op.f('ix_esg_policies_department_id'), table_name='esg_policies')
    op.drop_table('esg_policies')
    op.drop_index(op.f('ix_diversity_metrics_department_id'), table_name='diversity_metrics')
    op.drop_index('idx_dept_metric_period', table_name='diversity_metrics')
    op.drop_table('diversity_metrics')
    # ### end Alembic commands ###
