"""Add Category model

Revision ID: e77c082c2909
Revises: c56ffa0cdeea
Create Date: 2026-07-12 13:06:08.271393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e77c082c2909'
down_revision: Union[str, None] = 'c56ffa0cdeea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_code', sa.String(length=20), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('category_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name', 'category_type', name='uq_category_name_type')
    )
    op.create_index(op.f('ix_categories_category_code'), 'categories', ['category_code'], unique=True)
    op.create_index(op.f('ix_categories_category_name'), 'categories', ['category_name'], unique=False)
    op.create_index(op.f('ix_categories_category_type'), 'categories', ['category_type'], unique=False)
    op.create_index(op.f('ix_categories_status'), 'categories', ['status'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_status'), table_name='categories')
    op.drop_index(op.f('ix_categories_category_type'), table_name='categories')
    op.drop_index(op.f('ix_categories_category_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_category_code'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
